const ACTIONS = {
  ERROR: 10,
  CREATING_ROOM: 0,
  JOINING_ROOM: 1,
  START_GAME: 2,
  MAKING_MOVE: 3,
  ANNOUNCING_WINNER: 4,
  REMOVE_ROOM: 5,
  RESTART_GAME: 6,
  SYNCHRONIZE: 7,
  PLAYER_INFO: 8,
};

const ERROR_CODES = {
  GAME_NOT_FOUND: 6901,
  ROOM_ALREADY_CREATED: 6902,
  FULL_ROOM: 6903,
  NOT_A_PARTICIPANT: 6904,
  NOT_YOUR_TURN: 6905,
  INCORRECT_MOVE: 6906,
  GAME_HASNT_STARTED: 6907,
};

const RESPONSE_CODES = {};

module.exports = {
  ACTIONS,
  ERROR_CODES,
};
